/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define WWDG_IRQHandler wwdg_isr
#define PVD_PVM_IRQHandler pvd_pvm_isr
#define TAMP_STAMP_IRQHandler tamp_stamp_isr
#define RTC_WKUP_IRQHandler rtc_wkup_isr
#define FLASH_IRQHandler flash_isr
#define RCC_IRQHandler rcc_isr
#define EXTI0_IRQHandler exti0_isr
#define EXTI1_IRQHandler exti1_isr
#define EXTI2_IRQHandler exti2_isr
#define EXTI3_IRQHandler exti3_isr
#define EXTI4_IRQHandler exti4_isr
#define DMA1_CHANNEL1_IRQHandler dma1_channel1_isr
#define DMA1_CHANNEL2_IRQHandler dma1_channel2_isr
#define DMA1_CHANNEL3_IRQHandler dma1_channel3_isr
#define DMA1_CHANNEL4_IRQHandler dma1_channel4_isr
#define DMA1_CHANNEL5_IRQHandler dma1_channel5_isr
#define DMA1_CHANNEL6_IRQHandler dma1_channel6_isr
#define DMA1_CHANNEL7_IRQHandler dma1_channel7_isr
#define ADC_IRQHandler adc_isr
#define DAC_IRQHandler dac_isr
#define RESERVED_IRQHandler reserved_isr
#define COMP_IRQHandler comp_isr
#define EXTI9_5_IRQHandler exti9_5_isr
#define TIM1_BRK_IRQHandler tim1_brk_isr
#define TIM1_UP_IRQHandler tim1_up_isr
#define TIM1_TRG_COM_IRQHandler tim1_trg_com_isr
#define TIM1_CC_IRQHandler tim1_cc_isr
#define TIM2_IRQHandler tim2_isr
#define TIM16_IRQHandler tim16_isr
#define TIM17_IRQHandler tim17_isr
#define I2C1_EV_IRQHandler i2c1_ev_isr
#define I2C1_ER_IRQHandler i2c1_er_isr
#define I2C2_EV_IRQHandler i2c2_ev_isr
#define I2C2_ER_IRQHandler i2c2_er_isr
#define SPI1_IRQHandler spi1_isr
#define SPI2S2_IRQHandler spi2s2_isr
#define USART1_IRQHandler usart1_isr
#define USART2_IRQHandler usart2_isr
#define LPUART1_IRQHandler lpuart1_isr
#define LPTIM1_IRQHandler lptim1_isr
#define LPTIM2_IRQHandler lptim2_isr
#define EXTI15_10_IRQHandler exti15_10_isr
#define RTC_ALARM_IRQHandler rtc_alarm_isr
#define LPTIM3_IRQHandler lptim3_isr
#define RESERVED2_IRQHandler reserved2_isr
#define RESERVED3_IRQHandler reserved3_isr
#define RESERVED4_IRQHandler reserved4_isr
#define HSEM_IRQHandler hsem_isr
#define I2C3_EV_IRQHandler i2c3_ev_isr
#define I2C3_ER_IRQHandler i2c3_er_isr
#define RADIO_IRQHandler radio_isr
#define AES_IRQHandler aes_isr
#define TRNG_IRQHandler trng_isr
#define PKA_IRQHandler pka_isr
#define DMA2_CHANNEL1_IRQHandler dma2_channel1_isr
#define DMA2_CHANNEL2_IRQHandler dma2_channel2_isr
#define DMA2_CHANNEL3_IRQHandler dma2_channel3_isr
#define DMA2_CHANNEL4_IRQHandler dma2_channel4_isr
#define DMA2_CHANNEL5_IRQHandler dma2_channel5_isr
#define DMA2_CHANNEL6_IRQHandler dma2_channel6_isr
#define DMA2_CHANNEL7_IRQHandler dma2_channel7_isr
#define DMAMUX1_OVR_IRQHandler dmamux1_ovr_isr
